FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:${PATH}

RUN apt-get update && apt-get install -y \
    curl build-essential pkg-config ca-certificates libssl-dev \
    libasound2-dev libfontconfig1-dev \
    libxcb-shape0-dev libxcb-xfixes0-dev \
    && rm -rf /var/lib/apt-get/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path \
    && cargo install cargo-bundle \
    && chmod -R 777 $RUSTUP_HOME $CARGO_HOME

WORKDIR /app
