import { Palette, Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

// import "../assets/fonts/Chillax_Variable/Fonts/OTF/Chillax-Medium.otf";
import "../assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Medium.ttf";

export enum Page { SelectionPage, TimerPage, TimerFinished }
export enum StopType { TimerFinished, UserStopped }

component SelectionButton inherits Rectangle {
    in property <string> text;
    in property <length> font-size;

    callback clicked <=> touch.clicked;

    background: #C682F5;
    border-radius: 4px;

    txt := Text {
	text: root.text;
	font-size: root.font-size;
	color: black;
    }

    touch := TouchArea {}
}

export component MainWindow inherits Window {
    title: "Schisaciaccole";
    icon: @image-url("../assets/icon_256.png");
    preferred-width: 526px; 
    preferred-height: 326px;
    default-font-family: "Plus Jakarta Sans";
    // default-font-family: "Chillax";
    forward-focus: scope;


    property <float> ui-scale: Math.min(root.width / 526px, root.height / 326px);

    in-out property <duration> timer-time: 3s;
    in-out property <bool>     running-state: false;
    in-out property <Page>     page: SelectionPage; 
    in property     <bool>     is_fullscreen: false;
    in property     <[string]> time_options;


    callback start-pause();
    callback stop(StopType);
    callback select-time(int);
    callback compute-options();
    callback play-sound();
    callback set-selection-page();
    callback quit();
    callback fullscreen();

    scope := FocusScope {
        KeyBinding {
            keys: @keys(Q);
            activated => { quit(); }
        }

        KeyBinding {
            keys: @keys(M);
            activated => { fullscreen(); }
        }
    }

    timer := Timer {
	interval  : 1s;
	running: running-state;
	
	triggered() => {
	    if (running-state) {
		timer-time -= 1s;
		if (timer-time <= 0) {
		    stop(StopType.TimerFinished);
		    play-sound();
		}
	    } 
	}
    }

    compute-options-timer := Timer {
	interval  : 3s;
	running: !running-state;
	
	triggered() => {
	    // when the main timer is stopped keep updating the selection
	    compute-options();
	}
    }

    property <int> hours  : Math.floor(timer-time / 60s / 60);
    property <int> minutes: Math.floor(Math.mod(timer-time / 60s, 60));
    property <int> seconds: Math.mod(timer-time / 1s, 60);
    property <string> displayTimer: 
        (hours >= 1 ? "0" + hours + ":" : "") +
        (minutes < 10 ? "0" : "") + minutes + ":" +
        (seconds < 10 ? "0" : "") + seconds;



    // render this if page is SelectionPage
    if page == Page.SelectionPage : VerticalBox {
	alignment: center;
	padding: 25px * ui-scale;


	Text {
	    text: "Quando deve finire questa cerimonia?";
	    font-size: 22px * root.ui-scale;
	    horizontal-alignment: start;
	}

	GridLayout {
	    spacing: 15px * ui-scale;

	    for option[index] in root.time_options: SelectionButton {
		row: Math.floor(index / 4);
		col: Math.mod(index, 4);

		font-size: 18px * root.ui-scale;
		text: option;
		clicked => { select-time(index); }
	    }
	}
    }

    // render this if page is TimerPage
    if page == Page.TimerPage : VerticalBox {
	alignment: center;
	padding: 25px * ui-scale;


	Text {
	    text: displayTimer;
	    color: #C682F5;
	    font-size: 100px * root.ui-scale;
	    horizontal-alignment: center;
	}

	HorizontalBox {
	    alignment: center;

	    // Button {
	    // 	text: running-state ? "Pause" : "Start";
	    // 	clicked => { start-pause(); }
	    // }

	    Button {
		text: "Stop";
		clicked => { stop(StopType.UserStopped); }
	    }
	}
    }

    
    if page == Page.TimerFinished : VerticalBox {
	alignment: center;
	padding: 25px * ui-scale;


	Text {
	    text: "Congrats!\nScrum ceremony finished";
	    color: #C682F5;
	    font-size: 36px * root.ui-scale;
	    horizontal-alignment: center;
	}

	Text {
	    text: "Now get the fuck outta here";
	    color: #ffffff;
	    font-size: 24px * root.ui-scale;
	    horizontal-alignment: center;
	}


	HorizontalBox {
	    alignment: center;

	    Button {
		text: "Selection page";
		clicked => { set-selection-page(); }
	    }
	}
    }
    
}


export component StartWithZeroMillis inherits Window {
    title: "Schisaciaccole";
    preferred-width: 326px; 
    preferred-height: 226px;
    always-on-top: true;

    in property <string> widget-title;
    in property <string> widget-text;


    VerticalBox {
	alignment: center;

	Text {
	    // text: "You've been bad!";
	    text: widget-title;
	    color: red;
	    font-size: 32pt;
	    horizontal-alignment: center;
	}

	Text {
	    // text: "You can't start a timer with 0 seconds";
	    text: widget-text;
	    font-size: 18pt;
	    horizontal-alignment: center;
	}

	
    }
}
